- hosts: all
  gather_facts: true
  become: true
  pre_tasks:
    - name: Include global environment variables
      include_vars:
        file: env_vars/env.yml
        name: env_vars

  roles:
    - docker
    - create_network
    - launch_database
    - launch_app
    - launch_proxy
