name: CD DevOps Ansible 2025

on:
  workflow_run:
    workflows: ["CI Devops 2025"]
    types:
      - completed

jobs:
  play-ansible-playbook:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          # Private SSH key to register in the SSH agent
          ssh-private-key: ${{ secrets.SSH_PKEY }}
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify a version known to work well

      - name: Install Ansible and Docker SDK
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install docker

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          # Root directory of Ansible project (defaults to current)
          directory: ./TP3/ansible
          # Ansible playbook filepath
          playbook: ./playbook.yml
          # Custom content to write into hosts
          inventory: ./inventories/setup.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
                
