name: CD DevOps Ansible 2025

on:
  workflow_run:
    workflows: ["CI Devops 2025"]
    types:
      - completed

jobs:
  play-ansible-playbook:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify a version known to work well

      - name: Install Ansible and Docker SDK
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core==2.14
          pip install docker  # Install Docker SDK for Python if needed

      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install community.docker

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook -i TP3/ansible/inventories/setup.yml TP3/ansible/playbook.yml --become
