name: CD DevOps Ansible 2025

on:
  workflow_run:
    workflows: ["CI Devops 2025"]
    types:
      - completed

jobs:
  play-ansible-playbook:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Install Ansible Collections
        run: |
          ansible-galaxy collection install community.docker

      - name: Play Ansible Playbook
        uses: arillso/action.playbook@0.0.8
        with:
          inventory: TP3/ansible/inventories/setup.yml
          playbook: TP3/ansible/playbook.yml
          become: true
