name: CD DevOps 2025

on:
  workflow_run:
    workflows: "main"
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
      # Private SSH key to register in the SSH agent
        ssh-private-key: ${{ secrets.SSH_PKEY }}

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
      run: |
        cd TP3/ansible
        ansible-playbook -i inventories/setup.yml playbook.yml
