name: CI devops 2025
on:
  push:
    branches: main 
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'amazon'
          cache: maven

      - name: Build and test with Maven
        run: mvn clean verify --file ../../simple-api/pom.xml
